### ISSUE TITLE
使用插件的时候报错了，'Member' object has no attribute 'name'

### ISSUE THREAD

**Issue by fataldemon** [noneplugin/nonebot-plugin-userinfo#28]
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot\drivers\none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
 File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 90, in __call__
    values = await self.solve(**kwargs)
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 186, in solve
    values = await asyncio.gather(
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 174, in _solve_field
    value = await param._solve(**params)
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot\internal\params.py", line 221, in _solve
    return await task
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot_plugin_userinfo\getter.py", line 71, in dependency
    return await get_user_info(bot, event, event.get_user_id(), use_cache=use_cache)
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot_plugin_userinfo\getter.py", line 64, in get_user_info
    return await getter_tuple.getter(bot, event).get_info(
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot_plugin_userinfo\getter.py", line 34, in get_info
    info = await self._get_info(user_id)
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\nonebot_plugin_userinfo\adapters\satori.py", line 51, in _get_info
    member_name = member.name if member else None
  File "F:\GitRepository\AliceBot2\.venv\lib\site-packages\pydantic\main.py", line 828, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Member' object has no attribute 'name'

Chronocat版本是0.2.15，适配器是NoneBot-Adapter-Satori 0.12.3，Nonebot版本是2.3.2
是因为不支持吗

**Comment by MeetWq** [comment]
应该是 Satori 适配器有改动，可以暂时降级 Satori 适配器，或者等我修

**Comment by fataldemon** [comment]
降到哪个版本呢大佬，之前哪个版本是可用的

**Comment by MeetWq** [comment]
已更新
